POD1:
  - dstore : ESXi-POD1
  - host   : 172.16.11.13
  - R1     : 8kv_F1
  - R2     : 8kv_F2
  - R1_int1   : CSR1
  - R1_int2   : C1-1_B1-1
  - R1_int2   : C1-2_B2-2
  - R2_int1   : CSR2
  - R2_int2   : C2-1_B2-1
  - R2_int2   : C2-2_B1-2

POD2:
  - dstore : ESXi-POD2
  - host   : 172.16.21.13
  - R1     : 8kv_F1
  - R2     : 8kv_F2
  - R1_int1   : CSR1
  - R1_int2: C1-1_B1-1
  - R1_int2: C1-2_B2-2
  - R2_int1: CSR2
  - R2_int2: C2-1_B2-1
  - R2_int2: C2-2_B1-2

POD3:
  - dstore : ESXi-POD3
  - host   : 172.16.31.13
  - R1     : 8kv_F1
  - R2     : 8kv_F2
  - R1_int1: CSR1
  - R1_int2: C1-1_B1-1
  - R1_int2: C1-2_B2-2
  - R2_int1: CSR2
  - R2_int2: C2-1_B2-1
  - R2_int2: C2-2_B1-2

POD4:
  - dstore : ESXi-POD4
  - host   : 172.16.41.13
  - R1     : 8kv_F1
  - R2     : 8kv_F2
  - R1_int1: CSR1
  - R1_int2: C1-1_B1-1
  - R1_int2: C1-2_B2-2
  - R2_int1: CSR2
  - R2_int2: C2-1_B2-1
  - R2_int2: C2-2_B1-2
    
POD5:
  - dstore : ESXi-POD5
  - host   : 172.16.51.13
  - R1     : 8kv_F1
  - R2     : 8kv_F2
  - R1_int1: CSR1
  - R1_int2: C1-1_B1-1
  - R1_int2: C1-2_B2-2
  - R2_int1: CSR2
  - R2_int2: C2-1_B2-1
  - R2_int2: C2-2_B1-2
